version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Prebuild Server
          command: npm run prebuild
      - run: 
          name: Build Server
          command: npm build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
